export type TradeWithRelations = {
  id: string;
  userId: string;
  symbol: string;
  direction: "LONG" | "SHORT";
  status: "OPEN" | "CLOSED" | "CANCELLED";
  entryPrice: number;
  exitPrice: number | null;
  stopLoss: number;
  takeProfit: number | null;
  positionSize: number;
  entryTime: Date;
  exitTime: Date | null;
  riskAmount: number;
  riskPercent: number | null;
  realizedPnl: number | null;
  fees: number;
  rMultiple: number | null;
  setupId: string | null;
  tags: string[];
  entryTimeframe: string | null;
  session: "ASIA" | "LONDON" | "NEWYORK" | null;
  mae: number | null;
  mfe: number | null;
  followedRiskRule: boolean | null;
  followedRRTarget: boolean | null;
  withinDailyLimit: boolean | null;
  movedStop: boolean;
  emotionState: "CALM" | "FOMO" | "REVENGE" | "TILT" | "UNCERTAIN" | null;
  notes: string | null;
  createdAt: Date;
  updatedAt: Date;
  propChallengeId: string | null;
  setup: { id: string; name: string; color: string | null; description: string | null; userId: string } | null;
  screenshots: { id: string; url: string; tradeId: string; extracted: unknown }[];
  propChallenge: { id: string; firmName: string; phase: string | null } | null;
};
